name: InstallNextChecks

on:
  push:
    branches:
      - local
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: yarn build
